### PR TITLE
Add benchmark.md

### PR DESCRIPTION
**Pull request by qinxiongzhou**

### CODE REVIEW

**Review by megaeasex — APPROVED** [review]
[TASK:easegress-pr-test SUCCESS]megaease/easegress Pull Request 189 Deploy Test Success

**Comment by haoel** [comment]
Thanks for this PR,  I think we will combine this with #122  @benja-wu

**Review by megaeasex — APPROVED** [review]
[TASK:easegress-pr-test SUCCESS]megaease/easegress Pull Request 189 Deploy Test Success

**Comment by benja-wu** [comment]
Hi @qinxiongzhou, Thx for your contribution. 
I also find something interesting after reading your benchmark. Since we used golang-based `hey` tool to achieve stress testing, the result is quite different from yours. So I changed to use `ab` instead, here is what I found:

* In the same 4-core/32G memory AWS vms:
## ab baseline test
* Testing NGINX with `index.html`
``` bash
ab -c 100 -n 90000 http://172.20.2.35:8080/index.html                                      
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 172.20.2.35 (be patient)

Server Software:        nginx/1.18.0
Server Hostname:        172.20.2.35
Server Port:            8080

Document Path:          /index.html
Document Length:        612 bytes

Concurrency Level:      100
Time taken for tests:   4.155 seconds
Complete requests:      90000
Failed requests:        0
Total transferred:      76860000 bytes
HTML transferred:       55080000 bytes
Requests per second:    21662.91 [#/sec] (mean)
Time per request:       4.616 [ms] (mean)
Time per request:       0.046 [ms] (mean, across all concurrent requests)
Transfer rate:          18066.53 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    2   0.2      2       7
Processing:     0    3   0.5      3      13
Waiting:        0    2   0.5      2      12
Total:          0    5   0.4      5      15
```
* Testing Easegress with `index.html` liked API
``` bash
ab -c 100 -n 90000 http://172.20.2.35:10080/pipeline                                              
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Server Software:        
Server Hostname:        172.20.2.35
Server Port:            10080

Document Path:          /pipeline
Document Length:        651 bytes

Concurrency Level:      100
Time taken for tests:   4.279 seconds
Complete requests:      90000
Failed requests:        0
Total transferred:      69120000 bytes
HTML transferred:       58590000 bytes
Requests per second:    21032.13 [#/sec] (mean)
Time per request:       4.755 [ms] (mean)
Time per request:       0.048 [ms] (mean, across all concurrent requests)
Transfer rate:          15774.09 [Kbytes/sec] received

```
## hey baseline test
* Testing NGINX with `index.html`
``` bash
./hey -c 100 -n 90000 http://172.20.2.35:8080/index.html                                          

Summary:
  Total:	5.6858 secs
  Slowest:	0.1286 secs
  Fastest:	0.0001 secs
  Average:	0.0061 secs
  Requests/sec:	15828.9078
```
* Testing Easegress with `index.html` liked API
``` bash
./hey -c 100 -n 90000 http://172.20.2.35:10080/pipeline                                          

Summary:
  Total:	2.4175 secs
  Slowest:	0.0852 secs
  Fastest:	0.0001 secs
  Average:	0.0026 secs
  Requests/sec:	37228.5084
  
``` 

## Summary
* Same software, same environment, and configuration, but different stress-testing tools, it seems that `hey` implemented in Golang did help the Golang-based Easegress to perform better. **Need more investigation here**. 
* With `ab`, when the concurrency level raises to `200`, `300`, the CPU consuming of Easegress will be far heavier than NGINX, so the performance gap will become larger.
* I would like to combe your benchmark content into #122 's one third-party stress testing section, how about that? :-)

**Comment by zhao-kun** [comment]
@qinxiongzhou hi, Look like the pr conflicts with the main branch. We would very much appreciate it if you help to resolve it via renaming the `benchmark.md` to `benchmark-thirdparts.md`

**Pull request closed without merging**
