### PR TITLE
update roadmap for 2022

### PR DESCRIPTION
**Pull request by localvar**

### CODE REVIEW

**Review by xxx7xxxx — COMMENTED** [review]
I have some improvements in my backup list, @localvar could decide whether to add (part of) them into the roadmap:

1. Eliminate global components(such as logger) in order to get a better experience of unit testing, even we need a global/simple unit testing framework for Easegress itself.
2. API layer uses standard json(generated by protobuf), and CLI could produce/consume both yaml and json like kubectl.
3. Make json schema failure messages more readable(current ones are not indexed).
4. Support updating config for system controller.
5. Clarify the location of config and status of static config (https://github.com/megaease/easegress/pull/441#issuecomment-1001953374).

**Comment by jxd134** [comment]
>

**Comment by jxd134** [comment]
> I have some improvements in my backup list, @localvar could decide whether to add (part of) them into the roadmap:
> 
>     1. Eliminate global components(such as logger) in order to get a better experience of unit testing, even we need a global/simple unit testing framework for Easegress itself.
> 
>     2. API layer uses standard json(generated by protobuf), and CLI could produce/consume both yaml and json like kubectl.
> 
>     3. Make json schema failure messages more readable(current ones are not indexed).
> 
>     4. Support updating config for system controller.
> 
>     5. Clarify the location of config and status of static config ([#441 (comment)](https://github.com/megaease/easegress/pull/441#issuecomment-1001953374)).

I strongly agree with the second/third point.
In addition, we need to create multiple types of http filters, such as session sticky filter.

**Comment by localvar** [comment]
> I have some improvements in my backup list, @localvar could decide whether to add (part of) them into the roadmap:
> 
> 1. Eliminate global components(such as logger) in order to get a better experience of unit testing, even we need a global/simple unit testing framework for Easegress itself.
> ...
(https://github.com/megaease/easegress/pull/441#issuecomment-1001953374)).

We have `logger.InitNop` to create a nop logger for the unit test, so, do we still need the 1st one?

**Comment by suchen-sci** [comment]
we also have `logger.InitMock` to print log to stdout for the unit test to debug...

**Comment by xxx7xxxx** [comment]
> We have logger.InitNop to create a nop logger for the unit test, so, do we still need the 1st one?

IMHO, yes. My deep opinion is actually we need to make logger modularized and automatical environment perception, for example:

```go
func (rl *RateLimiter) Init() {
    // ...
    if x {
        // It prints `[filter/RateLimiter/ratelimiter-001]: BUG: duration is invalid` to stderr and file stdout.log.
        // But in unit testing, it prints the same message to the stderr only.
        rl.Log().Bugf("duration is invalid")
        return
    }

    // It prints `[filter/RateLimiter/ratelimiter-001]: initialization completed`.
    // The printing endpoint chosen are the same above.
    rl.Log().Infof("initialization completed")
}
```

And object/supervisor/cluster and so on got different prefixes for their own module/scope, I know it seems a little complex for Golang stuff. But as Easegress codebase inflates, the modularized logger should be the road ahead.

**Review by suchen-sci — APPROVED** [review]

**Comment by localvar** [comment]
updated according to comments.

For "API layer uses standard json(generated by protobuf)", I think it has been covered by "Protobuf models generating".
And I didn't include "Clarify the location of config and status of static config" in the roadmap, because I think it is not user awarable change.

**Review by samutamm — APPROVED** [review]

**Comment by xxx7xxxx** [comment]
How about adding `modularized logger` which is not the completely same as the better unit testings?

**Comment by localvar** [comment]
added.

> How about adding `modularized logger` which is not the completely same as the better unit testings?

**Review by xxx7xxxx — APPROVED** [review]

**Review by suchen-sci — APPROVED** [review]

**Pull request merged**
