### PR TITLE
[pr-test] add exist 0 for Jenkins pipeline

### PR DESCRIPTION
**Pull request by benja-wu**
Fix Jenkins pipeline stuck after finished executing test script.

### CODE REVIEW

**Review by localvar — APPROVED** [review]

**Review by danfu3000 — APPROVED** [review]

**Review by megaeasex — CHANGES_REQUESTED** [review]
[TASK:easegress-pr-test FAILED]megaease/easegress Pull Request 142 Deploy Test failed

**Review by megaeasex — APPROVED** [review]
[TASK:easegress-pr-test SUCCESS]megaease/easegress Pull Request 142 Deploy Test Success

**Review by megaeasex — CHANGES_REQUESTED** [review]
[TASK:easegress-pr-test FAILED]megaease/easegress Pull Request 142 Deploy Test failed

**Review by megaeasex — APPROVED** [review]
[TASK:easegress-pr-test SUCCESS]megaease/easegress Pull Request 142 Deploy Test Success

**Pull request merged**
