### PR TITLE
Create BENCHMARK.md

### PR DESCRIPTION
**Pull request by tg123**
benchmark report comparing windows and linux build

### CODE REVIEW

**Review by megaeasex — APPROVED** [review]
[TASK:easegress-pr-test SUCCESS]megaease/easegress Pull Request 145 Deploy Test Success

**Comment by johz-chen** [comment]
see:
https://doc.traefik.io/traefik/v1.4/benchmarks/#:~:text=sec%3A%203.14MB-,Conclusion,gives%20a%20ratio%20of%2085%25.

**Comment by benja-wu** [comment]
@tg123  Hi, since we had written the same purpose doc from a different angle. I will merge this MD's content into #122 . Thx

**Comment by benja-wu** [comment]
Merged this PR's content into #122, so close this PR.

**Pull request closed without merging**
