### PR TITLE
[reqAdaptor] add setting host support in reqAdaptor

### PR DESCRIPTION
**Pull request by benja-wu**
Supporting users set wanted HTTP Host value in the header. 
related issue #27

### CODE REVIEW

**Comment by localvar** [comment]
the documentation needs to be updated together.

**Comment by benja-wu** [comment]
> the documentation needs to be updated together.

Forgotten, sorry.

**Review by localvar — APPROVED** [review]

**Comment by zhao-kun** [comment]
Why not related to the issue?

**Review by xxx7xxxx — APPROVED** [review]

**Comment by benja-wu** [comment]
> Why not related to the issue?

updated

**Pull request merged**
