### PR TITLE
UDP and TCP clients for testing

### PR DESCRIPTION
**Pull request by samutamm**
Add dummy TCP and UDP clients to facilitate reviewing and testing https://github.com/megaease/easegress/pull/234.

### Dummy TCP test
Simple TCP test case on single machine:

1. Start easegress-server (based on https://github.com/megaease/easegress/pull/234) and create following object:

```yaml
kind: TCPServer
name: tcp-server-demo
port: 10080
maxConns: 1024
connectTimeout: 3000
pool:
  servers:
    - url: '127.0.0.1:9095'
  loadBalance:
    policy: roundRobin
```

2. Start dummy TCP backend proxy `go run example/backend-service/echo/echo.go tcp`
3. Run dummy TCP client program `go run example/client/tcp_udp.go tcp`
4. Observe messages passing.

### Dummy UDP test

1. Start easegress-server and create following object:

```yaml
kind: UDPServer
name: udp-server-demo
port: 10070
maxConns: 1024
hasResponse: true
clientIdleTimeout: 30000
serverIdleTimeout: 30000
pool:
  servers:
    - url: '127.0.0.1:9095'
  loadBalance:
    policy: roundRobin
ipFilters:
  blockByDefault: false
  allowIPs:
    - 127.0.0.1
```
2. Run `go run example/backend-service/echo/echo.go udp`
3. Run `go run example/client/tcp_udp.go udp`
4. Observe messages passing.

### CODE REVIEW

**Comment by localvar** [comment]
@samutamm , I think we should merge this PR after the TCP/UDP pr, because there's no TCPServer or UDPServer yet.

or, could @jxd134 help add the dummy clients to the TCP/UDP pr directly?

**Comment by jxd134** [comment]
> @samutamm , I think we should merge this PR after the TCP/UDP pr, because there's no TCPServer or UDPServer yet.
> 
> or, could @jxd134 help add the dummy clients to the TCP/UDP pr directly?

It will be all right.
See how @samutamm choose.

**Comment by samutamm** [comment]
> > @samutamm , I think we should merge this PR after the TCP/UDP pr, because there's no TCPServer or UDPServer yet.
> > or, could @jxd134 help add the dummy clients to the TCP/UDP pr directly?
> 
> It will be all right. See how @samutamm choose.

@jxd134 It would be simpler if you include this kind of dummy clients and maybe the echo server modifications to [PR](https://github.com/megaease/easegress/pull/234), then we could close this PR.

**Comment by jxd134** [comment]
> > > @samutamm , I think we should merge this PR after the TCP/UDP pr, because there's no TCPServer or UDPServer yet.
> > > or, could @jxd134 help add the dummy clients to the TCP/UDP pr directly?
> > 
> > 
> > It will be all right. See how @samutamm choose.
> 
> @jxd134 It would be simpler if you include this kind of dummy clients and maybe the echo server modifications to #234, then we could close this PR #448 .

Get it.

**Comment by samutamm** [comment]
Close as changes included in #234

**Pull request closed without merging**
