### PR TITLE
[release] v1.0.1

### PR DESCRIPTION
**Pull request by benja-wu**

### CODE REVIEW

**Comment by zhao-kun** [comment]
Please supply ChangeLog.md

**Comment by benja-wu** [comment]
Will add ChangeLog.md after this PR been merged and tagged with `v1.0.1`.

**Review by xxx7xxxx — APPROVED** [review]

**Comment by benja-wu** [comment]
The `goreleaser` will failed at trying to build `386` plaftform's image
```bash
• building         binary=/Users/benja/programmer/github/easegress/dist/server_linux_386/bin/easegress-server
   • building         binary=/Users/benja/programmer/github/easegress/dist/server_linux_arm64/bin/easegress-server
  ⨯ release failed after 227.89s error=failed to build for linux_386: # github.com/Shopify/sarama
../../go/pkg/mod/github.com/!shopify/sarama@v1.29.0/gssapi_kerberos.go:62:10: constant 4294967295 overflows int
```
So we need to ignore  the `386` platform in goreleaser's yaml.

**Review by localvar — APPROVED** [review]

**Comment by Loyalsoldier** [comment]
You should upgrade github.com/Shopify/sarama https://github.com/megaease/easegress/pull/66 to fix build failed.

**Comment by benja-wu** [comment]
> You should upgrade github.com/Shopify/sarama #66 to fix build failed.

Thanks for the reminder.

**Pull request merged**
