### PR TITLE
refactor mesh master

### PR DESCRIPTION
**Pull request by localvar**
* avoid redundant logs (this has also been done by another PR, this PR changes to way to do it.)
* delete dead instances faster
* fix minor race conditions (dead instances may be added back)
* avoid deep nesting

### CODE REVIEW

**Review by megaeasex — APPROVED** [review]
[TASK:easegress-pr-test SUCCESS]megaease/easegress Pull Request 357 Deploy Test Success

**Review by megaeasex — CHANGES_REQUESTED** [review]
[TASK:easegress-PR-test FAILED]megaease/easegress Pull Request 357 Deploy Test failed

**Comment by xxx7xxxx** [comment]
Please resolve the conflict, then we could review it. @localvar

**Comment by localvar** [comment]
conflicts have been resolved.

**Review by xxx7xxxx — APPROVED** [review]

**Pull request merged**
