### PR TITLE
RequestAdaptor support HeaderTemplate

### PR DESCRIPTION
**Pull request by hhhcj**
Another way to solve #903 , besides #905

### CODE REVIEW

**Comment by suchen-sci** [comment]
Hi, thanks a lot for your contribution! 

To support templates in `RequestAdaptor`, I prefer to support template in all specs of `RequestAdaptor`, not headers only. Any idea here?

**Comment by hhhcj** [comment]
> To support templates in RequestAdaptor, I prefer to support template in all specs of RequestAdaptor, not headers only. 

Glad to do that. I'll resubmit this pr days later.

**Comment by samanhappy** [comment]
Hi guys, I agree that we need to support template in a uniform way, but there are different ways to do it according to me

- Solution A(Template Building): use one template to build a complete `RequestAdaptor` like what we are doing in `RequestBuilder`
  - Pros: easy, same solution
  - Cons: less readable and less convenient when user only want to use one or less values

- Solution B(Templates/Variables Injecting): use syntax `{{}}` to inject template values or `${}` to inject variables
  - Pros: more readable and convenient
  - Cons: more work to do, different solutions
  
How do you think about it @localvar @suchen-sci @hhhcj?

**Comment by localvar** [comment]
hi @samanhappy , for solution B, could you please add an example?

and no matter which solution we choose, we need also update the `ResponseAdaptor` together.

for this PR, files in the `builder` folder have been modified and become a dependency of `RequestAdaptor`, this is not a good practice, if we want to reuse the code, a better way is to refactor the code and move the shared code to a separate package.



> Hi guys, I agree that we need to support template in a uniform way, but there are different ways to do it according to me
> 
> * Solution A(Template Building): use one template to build a complete `RequestAdaptor` like what we are doing in `RequestBuilder`
>   
>   * Pros: easy, same solution
>   * Cons: less readable and less convenient when user only want to use one or less values
> * Solution B(Templates/Variables Injecting): use syntax `{{}}` to inject template values or `${}` to inject variables
>   
>   * Pros: more readable and convenient
>   * Cons: more work to do, different solutions
> 
> How do you think about it @localvar @suchen-sci @hhhcj?

**Comment by samanhappy** [comment]
In my view, solution B can inject values directly like
```
kind: RequestAdaptor
name: request-adaptor-example
header:
  add: 
    token_from_template: {{.requests.DEFAULT.Header.token}}
    token_from_variable: ${token}
```
by the way, the variable references can be combined with `ResultBuilder` if possible.

**Comment by hhhcj** [comment]
After I made a pr #910 , I saw this conversaion.
How about we move both `RequestAdpator` and `ResponseAdaptor` to the builder folder, as DataBuilder , RequestBuilder, ResponseBuilder, ResultBuilder do.  @localvar 
> and no matter which solution we choose, we need also update the `ResponseAdaptor` together.
> 
> for this PR, files in the `builder` folder have been modified and become a dependency of `RequestAdaptor`, this is not a good practice, if we want to reuse the code, a better way is to refactor the code and move the shared code to a separate package.

**Comment by localvar** [comment]
> After I made a pr #910 , I saw this conversaion. How about we move both `RequestAdpator` and `ResponseAdaptor` to the builder folder, as DataBuilder , RequestBuilder, ResponseBuilder, ResultBuilder do. @localvar
> 
> > and no matter which solution we choose, we need also update the `ResponseAdaptor` together.
> > for this PR, files in the `builder` folder have been modified and become a dependency of `RequestAdaptor`, this is not a good practice, if we want to reuse the code, a better way is to refactor the code and move the shared code to a separate package.

this is an option, but we need to take all things into account before we make the final decision.

**Comment by hhhcj** [comment]
I didn't find much difference between solution A and B. Injecting template values is just what uniform template do. No matter you inject one value or inject whole values, the template parsing is needed.

> Hi guys, I agree that we need to support template in a uniform way, but there are different ways to do it according to me
> 
> * Solution A(Template Building): use one template to build a complete `RequestAdaptor` like what we are doing in `RequestBuilder`
>   
>   * Pros: easy, same solution
>   * Cons: less readable and less convenient when user only want to use one or less values
> * Solution B(Templates/Variables Injecting): use syntax `{{}}` to inject template values or `${}` to inject variables
>   
>   * Pros: more readable and convenient
>   * Cons: more work to do, different solutions
> 
> How do you think about it @localvar @suchen-sci @hhhcj?

**Comment by hhhcj** [comment]
We can seperate the solving issuer #903 and making a refactor as two different things. Supporting a uniform template will make a heavy test requirement  and may be blocked by some unexpected problems when adapting to one or more filter. It makes a long-term conversation and testing to some extent. 
We can find an easy and moderate way to fix issuer #903 , and then go on thinking about how to make a uniform template and refactor. 
> this is an option, but we need to take all things into account before we make the final decision.

**Comment by localvar** [comment]
> We can seperate the solving issuer #903 and making a refactor as two different things. Supporting a uniform template will make a heavy test requirement and may be blocked by some unexpected problems when adapting to one or more filter. It makes a long-term conversation and testing to some extent. We can find an easy and moderate way to fix issuer #903 , and then go on thinking about how to make a uniform template and refactor. @localvar
> 
> > this is an option, but we need to take all things into account before we make the final decision.

This is another option: backward compatibility is a requirement of Easegress, if the solution takes two steps, then we must make sure they are compatible.

**Comment by hhhcj** [comment]
> 
> This is another option: backward compatibility is a requirement of Easegress, if the solution takes two steps, then we must make sure they are compatible.

Pr #910 supplies template support for RequestAdaptor as RequestBuilder does. For the backward compatibility, we need update ResponseAdaptor together. Considering the builder folder have been modified and become a dependency of RequestAdaptor, #910  move the RequestAdaptor to the builder folder. 

In addition, sourceNamespace and template are mutually exclusive in the  RequestBuilder, but template will override the static params in pr #910 for the flexible. For consistency, we could change the exclusive clause in RequestBuilder and ResponseBuilder, or update #910 for the compliance with the exclusive clause. @localvar

**Comment by localvar** [comment]
close as duplicated with #910

**Pull request closed without merging**
