### PR TITLE
Fix: main package redeclaration in backend-service dir

### PR DESCRIPTION
**Pull request by Loyalsoldier**

### CODE REVIEW

**Comment by benja-wu** [comment]
Well, actually, in the `demoing/testing` scenario, we prefer to use `go run example/backend-service/mirror.go` or `go run example/backend-service/remote.go` directly for dedicated demo/test case. So we don't need to make the `backend-service` dir compilable. 
Still thanks for your concern and contribution. But I will close this PR as it's not necessary for our `demoing/testing` secnario.

**Comment by Loyalsoldier** [comment]
If not to change this, running `go vet ./...` will be failed with `main package redeclaration` error.

**Comment by benja-wu** [comment]
Ok, I misunderstood your purpose here. Let me reopen and review it. 

And maybe we can add more description in the PR comment to avoid such kind of communication problem. Thx :-)

**Review by benja-wu — APPROVED** [review]
LGTM

**Pull request merged**
